### ISSUE TITLE
Account info

### ISSUE THREAD

**Issue by pimstolk** [evanjd/python-logi-circle#7]
logi = LogiCircle(client_id='your-client-id',
                  client_secret='your-client-secret',
                  redirect_uri='https://your-redirect-uri',
                  api_key='your-api-key')

https://accounts.logi.com/identity/oauth2/authorize?response_type=code&client_secret=your-client-secret&redirect_uri=https%3A%2F%2Fyour-redirect-uri&scope=circle%3Aactivities_basic+circle%3Aactivities+circle%3Aaccessories+circle%3Aaccessories_ro+circle%3Alive_image+circle%3Alive+circle%3Anotifications+circle%3Asummaries&client_id=your-client-id

So where do i get all this info from? Looking trough all the headers doesn't really help me.
Wich one do you want me to use for "your-client-id"?

**Comment by evanjd** [comment]
Hi! Take a look at the README, relevant part quoted below:

> **The API this library wraps is not yet publicly available**. If you want something you can use today, check out the [v0.1 branch](https://github.com/evanjd/python-logi-circle/tree/v0.1.x). Please note that v0.1.x wraps Logitech's private API and won't be supported once the public API is released.

I'm currently polishing up the Home Assistant integration which includes instructions on requesting API access from Logitech. Once that's ready, the instructions included with that integration will include a link to request a client ID, secret and API key. For now, you can use the 0.1.x branch.

**Comment by pimstolk** [comment]
✅ Thanks for the reply, makes sense....
Now its time for me to feed to livestream to VLC.

**Comment by evanjd** [comment]
Instructions for requesting API access are now available on the [HA integration page](https://www.home-assistant.io/components/logi_circle/#requesting-api-access). Closing.
