### ISSUE TITLE
using Branch v0.1.x  if  dont have api access

### ISSUE THREAD

**Issue by sanariaz154** [evanjd/python-logi-circle#8]
this is follow up of the issue https://github.com/evanjd/python-logi-circle/issues/7 . I currently do not have the API key for logo circle but I need to set up remote access through python. Is the v0.1 is still working and supported?

**Comment by evanjd** [comment]
Best thing would be to try and see for yourself. I’m not supporting 0.1.x actively since the API it targets is private and could change at any time, but feel free to open an issue if something is broken and I’ll take a look.
